--This file should be generated by Python before DBT runs

{{ config(materialized='view', tags=['gold','params']) }}

{% set driver_id     = var('driver_id', 'hamilton') %}
{% set season_year   = var('season_year', 2022) %}

select
  '{{ driver_id }}'::text  as driver_id,
  {{ season_year }}::int   as season_year